// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, NextImage, withDatasourceCheck, Placeholder, RichText, withSitecore, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useEffect, useState } from 'react';
import React from 'react';
import { isEnabled } from 'src/helpers/isEnabled';
import BlobAccent from 'src/components/shapes/BlobAccent';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight, faBars, faChevronDown, faChevronUp, faTimes, faEnvelope, faPhone, faArrowLeft } from '@fortawesome/free-solid-svg-icons';
import CurvedClip from 'src/components/shapes/CurvedClip';
import HeroClip from 'src/components/shapes/HeroClip';
import { useI18n } from 'next-localization';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { faFacebook, faInstagram, faTwitter } from '@fortawesome/free-brands-svg-icons';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Keyboard, Navigation, Pagination } from 'swiper/modules';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'NextImage', value: NextImage },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'withSitecore', value: withSitecore },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'src/helpers/isEnabled',
    exports: [
      { name: 'isEnabled', value: isEnabled },
    ]
  },
  {
    module: 'src/components/shapes/BlobAccent',
    exports: [
      { name: 'default', value: BlobAccent },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: '@fortawesome/free-solid-svg-icons',
    exports: [
      { name: 'faArrowRight', value: faArrowRight },
      { name: 'faBars', value: faBars },
      { name: 'faChevronDown', value: faChevronDown },
      { name: 'faChevronUp', value: faChevronUp },
      { name: 'faTimes', value: faTimes },
      { name: 'faEnvelope', value: faEnvelope },
      { name: 'faPhone', value: faPhone },
      { name: 'faArrowLeft', value: faArrowLeft },
    ]
  },
  {
    module: 'src/components/shapes/CurvedClip',
    exports: [
      { name: 'default', value: CurvedClip },
    ]
  },
  {
    module: 'src/components/shapes/HeroClip',
    exports: [
      { name: 'default', value: HeroClip },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: '@fortawesome/free-brands-svg-icons',
    exports: [
      { name: 'faFacebook', value: faFacebook },
      { name: 'faInstagram', value: faInstagram },
      { name: 'faTwitter', value: faTwitter },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Keyboard', value: Keyboard },
      { name: 'Navigation', value: Navigation },
      { name: 'Pagination', value: Pagination },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
