---
ID: "af5fa9d5-4c52-48f8-94d6-1eb1243e075a"
Parent: "4a951247-f802-457e-b705-8baeed59e987"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/templates/Branches/Project/play/Default DoctorDetails Variant/$name/Default
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8acb521f-d8cd-424b-b152-602de9573d2f"
Languages:
- Language: "de-DE"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "ba331134-5ef3-442e-9ead-900576d44c4d"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Default
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50ac68e5-d155-4eae-a5cb-dec1828cfcca"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "468b0b1b-5a10-45e7-badb-351f3c31d6ef"
- Language: "ja-JP"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "ba331134-5ef3-442e-9ead-900576d44c4d"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: デフォルト
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50ac68e5-d155-4eae-a5cb-dec1828cfcca"
- Language: "zh-CN"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "ba331134-5ef3-442e-9ead-900576d44c4d"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 默认
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "50ac68e5-d155-4eae-a5cb-dec1828cfcca"
