export const THEME_PRESETS: Record<string, Record<string, string>> = {
  Default: {},
  Ocean: {
    '--color-background': '#e0f7fa',
    '--color-background-secondary': '#b2ebf2',
    '--color-background-tertiary': '#80deea',
    '--color-foreground': '#006064',
    '--color-background-dark': '#004d40',
    '--color-background-secondary-dark': '#00796b',
    '--color-background-tertiary-dark': '#004d40',
    '--color-foreground-dark': '#e0f7fa',
    '--color-foreground-secondary-dark': '#80deea',
    '--color-accent': '#26c6da',
    '--color-accent-muted': '#80deea',
    '--color-background-input': '#b2ebf2',
    '--color-disabled': '#cfd8dc',
    '--color-disabled-dark': '#4db6ac',
  },
  Sunset: {
    '--color-background': '#fff3e0',
    '--color-background-secondary': '#ffe0b2',
    '--color-background-tertiary': '#ffcc80',
    '--color-foreground': '#bf360c',
    '--color-background-dark': '#3e2723',
    '--color-background-secondary-dark': '#6d4c41',
    '--color-background-tertiary-dark': '#4e342e',
    '--color-foreground-dark': '#fff3e0',
    '--color-foreground-secondary-dark': '#ffcc80',
    '--color-accent': '#ff7043',
    '--color-accent-muted': '#ffab91',
    '--color-background-input': '#ffe0b2',
    '--color-disabled': '#d7ccc8',
    '--color-disabled-dark': '#8d6e63',
  },
  Midnight: {
    '--color-background': '#0d1b2a',
    '--color-background-secondary': '#1b263b',
    '--color-background-tertiary': '#415a77',
    '--color-foreground': '#e0e1dd',
    '--color-background-dark': '#000814',
    '--color-background-secondary-dark': '#1b263b',
    '--color-background-tertiary-dark': '#1f4068',
    '--color-foreground-dark': '#e0e1dd',
    '--color-foreground-secondary-dark': '#415a77',
    '--color-accent': '#ff6b6b',
    '--color-accent-muted': '#ff9f9f',
    '--color-background-input': '#1b263b',
    '--color-disabled': '#4b4b4b',
    '--color-disabled-dark': '#2c3e50',
  },
};

export const THEME_VARIABLES = [
  '--color-background',
  '--color-background-secondary',
  '--color-background-tertiary',
  '--color-foreground',
  '--color-background-dark',
  '--color-background-secondary-dark',
  '--color-background-tertiary-dark',
  '--color-foreground-dark',
  '--color-foreground-secondary-dark',
  '--color-accent',
  '--color-accent-muted',
  '--color-background-input',
  '--color-disabled',
  '--color-disabled-dark',
];
