---
ID: "824a724c-accd-4f43-8007-ede4ca193555"
Parent: "c5f93b76-90a7-45ba-9a39-36f0a3779ca2"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/play/play-healthcare/Presentation/Headless Variants/DoctorsListing/Default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c1b092ca-d339-4989-9cba-03fb20cd36c6"
