/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';

import { BYOCWrapper, FEaaSWrapper } from '@sitecore-jss/sitecore-jss-nextjs';
import { Form } from '@sitecore-jss/sitecore-jss-nextjs';

// import * as CdpPageView from '../../src/components/CdpPageView';
import * as ColumnSplitter from '../../src/components/ColumnSplitter';
import * as Container from '../../src/components/Container';
import * as ContentBlock from '../../src/components/ContentBlock';
import * as ContentSection from '../../src/components/ContentSection';
import * as DoctorDetails from '../../src/components/DoctorDetails';
import * as DoctorsListing from '../../src/components/DoctorsListing';
// import * as FEAASScripts from '../../src/components/FEAASScripts';
import * as Features from '../../src/components/Features';
import * as Footer from '../../src/components/Footer';
import * as Header from '../../src/components/Header';
import * as HeroBanner from '../../src/components/HeroBanner';
import * as Image from '../../src/components/Image';
import * as LinkList from '../../src/components/LinkList';
import * as Navigation from '../../src/components/Navigation';
import * as PageContent from '../../src/components/PageContent';
import * as PartialDesignDynamicPlaceholder from '../../src/components/PartialDesignDynamicPlaceholder';
import * as Promo from '../../src/components/Promo';
import * as RichText from '../../src/components/RichText';
import * as RowSplitter from '../../src/components/RowSplitter';
import * as Testimonials from '../../src/components/Testimonials';
import * as ThemeSwitcher from '../../src/components/ThemeSwitcher';
import * as Title from '../../src/components/Title';
import * as BlobAccent from '../../src/components/shapes/BlobAccent';
import * as CurvedClip from '../../src/components/shapes/CurvedClip';
import * as HeroClip from '../../src/components/shapes/HeroClip';

export const components = new Map();
components.set('BYOCWrapper', BYOCWrapper);
components.set('FEaaSWrapper', FEaaSWrapper);
components.set('Form', Form);

// components.set('CdpPageView', CdpPageView);
components.set('ColumnSplitter', ColumnSplitter);
components.set('Container', Container);
components.set('ContentBlock', ContentBlock);
components.set('ContentSection', ContentSection);
components.set('DoctorDetails', DoctorDetails);
components.set('DoctorsListing', DoctorsListing);
// components.set('FEAASScripts', FEAASScripts);
components.set('Features', Features);
components.set('Footer', Footer);
components.set('Header', Header);
components.set('HeroBanner', HeroBanner);
components.set('Image', Image);
components.set('LinkList', LinkList);
components.set('Navigation', Navigation);
components.set('PageContent', PageContent);
components.set('PartialDesignDynamicPlaceholder', PartialDesignDynamicPlaceholder);
components.set('Promo', Promo);
components.set('RichText', RichText);
components.set('RowSplitter', RowSplitter);
components.set('Testimonials', Testimonials);
components.set('ThemeSwitcher', ThemeSwitcher);
components.set('Title', Title);
components.set('BlobAccent', BlobAccent);
components.set('CurvedClip', CurvedClip);
components.set('HeroClip', HeroClip);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
